repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest version or specify your preferred one
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'  # Use the latest or a specific mypy version
    hooks:
      - id: mypy

  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'  # Use the latest or a specific flake8 version
    hooks:
      - id: flake8
        args: [--max-line-length=115]

  - repo: https://github.com/psf/black
    rev: '23.9.1'  # Use the latest or a specific version
    hooks:
      - id: black
        args: [--line-length=115]

  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: [--line-length=115]
